name: Validate and Deploy

on:
  push:
    branches: [master]
    paths:
      - 'Dockerfile'
      - 'app/**'
      - 'fly.toml'
      - 'public/**'
      - 'remix.config.js'
      - 'styles/**'
      - 'tailwind.config.js'

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.10.0'
          cache: 'npm'
      - name: Install Packages
        run: npm install
      - name: Validate
        run: npm run validate

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: superfly/flyctl-actions@1.3
        with:
          args: 'deploy'
